googleapis/elixir-google-api

config/config.exs

The improved elixir client codegen was merged in swagger codegen and the `swaggerapi/swagger-codegen-cli` image has the necessary changes.

Default image to community image.

---

README.md
lib/google_apis.ex
lib/google_apis/api_config.ex
lib/google_apis/converter/api_spec_converter.ex
lib/google_apis/directory_item.ex
lib/google_apis/discovery.ex
lib/google_apis/generator/swagger_cli.ex
lib/google_apis/swagger_config.ex
lib/mix/tasks/google_apis.build.ex
lib/mix/tasks/google_apis.convert.ex
lib/mix/tasks/google_apis.discover.ex
lib/mix/tasks/google_apis.fetch.ex

This PR includes the following changes:
* Adjust source code styles, most of the changes follow the [Elixir Style Guide](https://github.com/lexmag/elixir-style-guide)
* Fix some typos in the `README.md` file
* Re-wrap some paragraphs to fit 80-columns

Improve source code styles

---

clients/translate/mix.exs

Includes fix for the data wrapped return type #45

Version bump translate 0.0.3

---

.travis.yml
template/api.mustache
template/deserializer.ex.mustache
template/mix.exs.mustache
template/model.mustache
template/request_builder.ex.mustache

Tested against the sheets API: https://github.com/chingor13/elixir-google-api/pull/1/files
#73

Fix typespecs for Dialyzer warnings

---

clients/gax/lib/google_api/gax/connection.ex
template/gax/connection.ex.mustache

See #58
Won't actually resolve the issue until we rebuild all clients with gax.

Read base url from application config

---

clients/gax/lib/google_api/gax/connection.ex
clients/gax/lib/google_api/gax/model_base.ex
clients/gax/lib/google_api/gax/response.ex
clients/gax/mix.exs
clients/gax/test/gax/response_test.exs
clients/test_client/mix.exs
scripts/ci.sh
template/gax/connection.ex.mustache
template/gax/mix.exs.mustache

When we rebuild the clients to use gax, we will also upgrade to Tesla 1.0
See #64

Update tesla to 1.0

---

clients/gax/lib/google_api/gax/connection.ex
clients/o_auth2/test/default_test.exs

Add default body to put/post/delete requests if no body set

---

clients/gax/lib/google_api/gax/request.ex
clients/gax/test/gax/request_test.exs

Query params should be repeated fields

---

clients/test_client/test/test_helper.exs
clients/test_client/test/type_test.exs
specifications/gdd/TestClient-v1.json
template/gax/model.mustache

Analytics API contains a list of list of a defined schema type. Currently the template creates invalid syntax.
For now, collections of collections of some type are not extracted into that deeply nested type. See #89

Nested containers

---

lib/google_apis/generator/swagger_cli.ex
mix.exs
mix.lock
template/gax/mix.exs.mustache

Files generated in a mounted workspace in docker are owned by root. When
we copy them, our new versions will be owned by our current user and can
be modified further.

Generate files into a temp directory and copy into final location.

---

clients/gax/README.md
clients/gax/mix.exs

Relax tesla dependency

---

lib/google_apis/generator/swagger_cli.ex
scripts/generate_client.sh
synth.py

This will allow autogeneration to happen from autosynth

Use docker in synth script

---

.kokoro/release.cfg
.kokoro/release.sh
clients/books/README.md
clients/books/mix.exs
config/apis.json
config/config.exs
lib/google_apis.ex
lib/google_apis/api_config.ex
lib/google_apis/publisher.ex
lib/mix/tasks/google_apis.publish.ex

Adds script that can run from Kokoro and release all packages that are not yet published.

Kokoro release

---

package.json

Sort global parameters alphabetically when converting

---

clients/test_client/lib/google_api/test_client/v1/api/objects.ex
clients/test_client/lib/google_api/test_client/v2/api/objects.ex
clients/test_client/test/api_test.exs
template/gax/api.mustache

Fix path variable encoding

---

.gitignore

Only ignore the root synth.metadata file

---

clients/cloud_run/.swagger-codegen-ignore

Add README and mix.exs to Cloud Run's codegen ignore file

---

clients/gax/mix.exs

Release gax 0.1.3

---

config/apis.json

See https://support.google.com/googleplay/android-developer/answer/6136246?hl=en
Fixes #2621

Remove dead AppState API from the list

---

config/apis.json

Remove dead UrlShortener API from the list

---

config/apis.json

Remove ServiceUser API from the autogen list

---

config/apis.json

Remove GamesConfiguration API

---

config/apis.json

fix(generator): Remove AndroidPublisher V2

---

clients/test_client/lib/google_api/test_client/v1/api/objects.ex
clients/test_client/lib/google_api/test_client/v2/api/objects.ex
clients/test_client/test/api_test.exs
lib/google_apis/generator/elixir_generator/parameter.ex
template/elixir/api.ex.eex
test/google_apis/generator/elixir_generator/parameter_test.exs

A path parameter may include slashes if it is the last path element. Fixes #4600.

fix(generator): allow slashes in the last path element
