googleapis/elixir-google-api

config/apis.json, lib/google_apis.ex, lib/google_apis/discovery.ex
When calling `mix google_apis.fetch` we now handle 404s from the API discovery service and continue processing.
=> Handle missing API definitions

clients/translate/lib/google_api/translate/v2/api/detections.ex, clients/translate/lib/google_api/translate/v2/api/languages.ex, clients/translate/lib/google_api/translate/v2/api/translations.ex, clients/translate/lib/google_api/translate/v2/deserializer.ex, clients/translate/lib/google_api/translate/v2/model/detect_language_request.ex, clients/translate/lib/google_api/translate/v2/model/detections_list_response.ex, clients/translate/lib/google_api/translate/v2/model/detections_resource.ex, clients/translate/lib/google_api/translate/v2/model/detections_resource_inner.ex, clients/translate/lib/google_api/translate/v2/model/get_supported_languages_request.ex, clients/translate/lib/google_api/translate/v2/model/languages_list_response.ex, clients/translate/lib/google_api/translate/v2/model/languages_resource.ex, clients/translate/lib/google_api/translate/v2/model/translate_text_request.ex, clients/translate/lib/google_api/translate/v2/model/translations_list_response.ex, clients/translate/lib/google_api/translate/v2/model/translations_resource.ex, clients/translate/lib/google_api/translate/v2/request_builder.ex, template/api.mustache
Fixes #38 
The api converter handles the `features[dataWrapper]` and converts to a `x-dataWrapper` vendor extension available for each operation.
If the x-dataWrapper option is present for an operation, we unwrap the data when deserializing using Poison.
=> Unwrap api response if the x-dataWrapper vendor extension is present

.travis.yml, lib/google_apis.ex, lib/mix/tasks/google_apis.format.ex, lib/mix/tasks/google_apis.generate.ex, mix.exs
* Add an additional mix task `mix google_apis.format [library-name]` - runs code formatter on the specified library (or all libraries if not provided)
* Add an additional mix task `mix google_apis.generate [library-name]` - rebuilds the specified library from scratch (download, convert, build, format).
=> Use elixir 1.6 code formatter

clients/translate/config/config.exs, clients/translate/lib/google_api/translate/v2/api/detections.ex, clients/translate/lib/google_api/translate/v2/api/languages.ex, clients/translate/lib/google_api/translate/v2/api/translations.ex, clients/translate/lib/google_api/translate/v2/request_builder.ex, clients/translate/mix.exs, clients/translate/test/test_helper.exs, clients/translate/test/translate_test.exs, template/api.mustache, template/request_builder.ex.mustache
For dataWrapped APIs (currently only Translate) we can create a shared `DataWrapper` struct that can decode itself with `Poison` via a provided `option[:struct]` type.
=> Fix dataWrapped return values

clients/firestore/README.md
google_cloud_firestore doesn't exist on Hex, google_api_firestore does
=> Fix hex link

clients/gax/lib/google_api/gax/model_base.ex
This was happening to me when calling `GoogleApi.Storage.V1.Api.Objects.storage_objects_insert_simple/5`
Elixir version: 1.8.1
From mix.lock:
```
"google_api_storage": {:hex, :google_api_storage, "0.1.0", "331a0186228edfc399fb6787236b1d73e1233b59c1c7318b3907e712dc0731cb", [:mix], [{:google_gax, "~> 0.1.0", [hex: :google_gax, repo: "hexpm", optional: false]}], "hexpm"},
"google_gax": {:hex, :google_gax, "0.1.1", "02a267deb0a43e4f1eadf197a22d90804136c1ea3519bf977cf5b0c093d111ef", [:mix], [{:poison, ">= 1.0.0", [hex: :poison, repo: "hexpm", optional: false]}, {:tesla, "~> 1.0", [hex: :tesla, repo: "hexpm", optional: false]}], "hexpm"},
```
```
** (FunctionClauseError) no function clause matching in DateTime.from_iso8601/2    
The following arguments were given to DateTime.from_iso8601/2: …
```
=> Fix to match even already parsed DateTime

clients/gax/README.md
`gax` package doesn't exist in hex.pm
`google_gax` is the correct package name
=> Use correct package name in gax README.md

lib/google_apis/generator/elixir_generator.ex, scripts/generate_client.sh, synth.py
We were leaving old files from the Swagger generator which are no longer necessary.
Also fixes all the failures caused by AndroidPublisher adding a new version. When we create a new directory (v3), the umask from the new directory in the working directory has the files owned by the root docker user. We cannot run `git clean` on that directory from outside the docker image.
=> Clean before code generation

config/apis.json, lib/google_apis/generator/elixir_generator.ex, lib/google_apis/generator/elixir_generator/parameter.ex, test/google_apis/generator/elixir_generator/parameter_test.exs
* AdExchangeSeller API was removed
* Fix handling APIs which don't define OAuth scopes
* Fix handling of variable names for parameters that contain dashes
=> Fix some failing generation

lib/google_apis/generator/elixir_generator.ex
In the swagger generator, the `otp_app` uses a snake-cased name of the API with underscores where there are multiple words. For example, the `UrlShortener` API has an `otp_app` of `google_api_url_shortener`. Currently the new generator uses the *API name* which generally concatenates words together without the underscore. So the new generator creates the name `google_api_urlshortener`. See e.g. https://github.com/googleapis/elixir-google-api/pull/1838/files#diff-50cb9b5f2a608a8edf65486a8894bdd3R30
I think we should prefer the earlier version with the underscore because it matches the Elixir namespace (e.g. `GoogleApi.UrlShortener`). So I'm grabbing that value from the token.
=> Fix otp_app name used in the config path

config/apis.json
Manually update or remove a bunch of APIs and versions that are no longer in discovery or have changed. This should resolve the YouTubeAnalytics weirdness (API apparently removed), and most of the current synthesis failures. (There are still a couple of synthesis failures that are unrelated and will have to be handled separately.)
This PR does NOT yet attempt to go through and add new versions/APIs that have since appeared or been made public. I think we should prepare an automated mechanism to do that, and will open an issue with some design ideas.
=> Update API list to address current synth failures

lib/google_apis/generator/elixir_generator/renderer.ex, template/elixir/api.ex.eex, template/elixir/model.ex.eex
Add some quoting when rendering description text into docstrings. Specifically:
* If triple quotes appear in the description, we backslash-escape each one. This prevents the triple quote from breaking the docstring syntax.
* If a literal backslash appears in the description, we backslash-escape it also, to preserve it in the docstring.
This should fix #1519.
=> Quote description content for inclusion in docstrings

clients/gax/lib/google_api/gax/connection.ex, clients/gax/lib/google_api/gax/data_wrapper.ex, clients/gax/lib/google_api/gax/request.ex, clients/gax/lib/google_api/gax/response.ex, clients/gax/mix.exs, clients/gax/test/gax/api_test.exs, clients/gax/test/gax/connection_test.exs, clients/gax/test/gax/request_test.exs, clients/gax/test/test_client/api/pets.ex
The main change here is proper support for the `x-goog-api-client` header. It includes:
`gl-elixir/#{ELIXIR_VERSION} gax/#{GAX_VERSION} gdcl/#{LIBRARY_VERSION}` where ELIXIR_VERSION is obtained by calling `System.version()` at runtime, and GAX_VERSION is obtained by calling `Mix.Project.config()` at _compile time_.
The LIBRARY_VERSION will need to be passed in by the downstream generated library. To this end, I added `library_version` as a field of `GoogleApi.Gax.Request`. It defaults to the empty string, which generates the correct `gdcl/` syntax for unknown version. (This will be the behavior when an older client uses this newer gax.) The next step will be to modify the generator to set this field when generating request structs. (Generated libraries will determine their proper value by …
=> feat(gax): Generate x-goog-api-client header

lib/google_apis/generator/elixir_generator.ex, lib/google_apis/generator/elixir_generator/renderer.ex, template/elixir/LICENSE.eex, template/elixir/gitignore.eex, template/elixir/mix.exs.eex
It looks like the lack of LICENSE is causing some of the releases to fail. This ensures every library has the file.
I also generated `.gitignore`, and tweaked the format of the hex description in generated `mix.exs` to include the discovery description (i.e. `Client library for <%= api_title %> from Google. <%= description %>`)
=> feat(generator): Generate LICENSE and .gitignore files

lib/google_apis/generator.ex, mix.exs, mix.lock
This rewrites the version bump mechanism to solve two issues.
1. It calls hex to get the current version from which to bump, instead of using the current value from mix.exs. This is to prevent "multiple bumps". (Note that if the hex call fails, it will still fall back to reading mix.exs.)
2. It updates both mix.exs and the README.md. This is important because README.md is now generated and its version requirement comes from mix.exs. The two need to stay in sync. (Thus, this prevents a "version update loop" in which the version is bumped in mix.exs, and then the next time generation is run, README.md gets updated, which in turn triggers another version bump.)
=> fix(generator): Version bump from actual hex version

lib/google_apis/generator/elixir_generator.ex, lib/google_apis/generator/elixir_generator/renderer.ex, template/elixir/mix.exs.eex
Fixes #2433 by changing the description field in the generated mix.exs to omit the "long" description from the discovery doc if it would have caused the field to exceed 299 characters.
Note: the first part of the description wording was also changed from `Client library for <%= api_title %> from Google` to `<%= api_title %> client library` which should be a bit less awkward. Note that #2440 makes the same change in the generated readme.
=> fix(generator): Limit hex description field to 299 characters

config/apis.json
Some initial edits to the api list:
* Add Firestore V1 (because I need it for a demo). This means Firestore will now include both V1 and V1beta1.
* Remove ReplicaPool which is long deprecated with a GA replacement, and I don't think we should generate it any longer.
I'm starting to look into a full refresh of the list, but first I want to update the generator to generate the remaining files, so we can let the generator create new libraries on its own.
=> chore(generator): Add firestore v1 and remove obsolete replicapool from api list

clients/firestore/README.md, clients/firestore/mix.exs
The last autosynth added v1 files but didn't bump the package version.
=> chore(firestore): Bump firestore version

README.md
One edit on the read me, for drive modules: `GoogleApi`  not `GoogleApis`
=> correct name for module

clients/gax/lib/google_api/gax/data_wrapper.ex, clients/gax/lib/google_api/gax/model_base.ex, clients/gax/mix.exs
Modify gax so it will run with either Poison 3 or Poison 4. Fixes #1232.
We check at compile time for `Poison.Decode.decode/2` which exists in Poison 3 but was renamed to `Poison.Decode.transform/2` in Poison 4, and generate different versions of the function `GoogleApis.Gax.ModelBase.poison_transform/2` in response, to call the appropriate Poison function.
This also includes two Poison 4 specific fixes:
* Poison's options are supposed to be of type `Map`. Most calls perform automatic conversion from `Keyword`, but `Poison.Decode.transform` doesn't. So we alter our call points accordingly.
* Poison 4 has an apparent known issue (https://github.com/devinus/poison/issues/191) where struct transformation happens twice on substructs (which causes failures because the transformation code …
=> Add support for Poison 4

lib/google_apis/generator/elixir_generator/endpoint.ex, test/google_apis/generator/elixir_generator/endpoint_test.exs
Currently, upload operations are generating three functions:
* the basic upload (which translates to metadata-only upload) using the base URL. For example `storage_objects_insert`.
* "simple" upload (which actually translates to multipart upload, providing both metadata and content, but pulling the content from a file) using the "simple" mediaUpload URL. For example `storage_objects_insert_simple`.
* "resumable" upload which uses the "resumable" mediaUpload URL. For example `storage_objects_insert_resumable`.
We're getting requests (e.g. #972) to be able to upload directly from memory rather than having to write to a file. So I'm causing the generation of a fourth function, called (for example) `storage_objects_insert_iodata`, which is like the simple case but takes an …
=> Generate function that uploads from iodata

clients/gax/README.md, clients/gax/lib/google_api/gax/response.ex, clients/gax/mix.exs, clients/gax/test/gax/response_test.exs
Handles the case when a call declares its return type as a particular struct, but the actual returned JSON is an array of that struct. Detects the array when deserializing (i.e. checks whether the first character is `[`) and alters the deserialization type accordingly.
This sometimes happens when the underlying RPC actually returns a stream. The REST version of such an RPC translates this to an array of data structures, but the discovery doc doesn't reflect that, so the generated code still thinks the return type is just a single struct. Fixes #1231 which reports one such case (Firestore's documents.runQuery call).
=> Handle array as toplevel response

config/apis.json, lib/google_apis/discovery.ex, lib/google_apis/generator/elixir_generator/endpoint.ex, lib/mix/tasks/google_apis.discover_update.ex, synth.py
Did a global update of the APIs list based on the current set of APIs from Discovery. Specifically:
* Removed 1 obsolete API (FusionTables, see #3020)
* Added all APIs/versions that are in the current "preferred" list from discovery but not in apis.json. (However, note that a few were omitted because they are obsolete or not public even though discovery still lists them: specifically, FusionTables, OSConfig, Plus, and PlusDomains.)
Additionally:
* Wrote another task, `google_apis.discover_update` which is similar to `google_apis.discover` but useful for updating the current list. Specifically, any APIs in the list that are no longer in discovery at all (i.e. not even non-preferred) are annotated with a "FIXME: remove" in the file, and any APIs that are in the preferred list from discovery …
=> Update apis list and ensure all apis generate

config/apis.json, synth.py
* Builds are broken because https://github.com/googleapis/synthtool/pull/370 removed the `depth=` argument. Fixed.
* SearchConsole has been failing because the discovery doc was removed. Removed it from the list.
=> Update builds for synthtool change, and remove SearchConsole from API list

lib/google_apis/generator/elixir_generator/resource_context.ex
Fixes #2434 
MachineLearning is affected, possibly one or two others. The issue involves types that are declared in the discovery doc using double-underscores (e.g. `GoogleCloudMlV1__ExplainRequest`). Model generation currently pushes these names through `Macro.camelize/1`, which shortens double-underscores to single-underscores. However, Api generation is not currently doing so for typespecs and references to those type modules, resulting in those references retaining the double underscores and thus failing to compile. This PR pushes those names through `Macro.camelize/1` to match the model definitions.
The original idea in #2434 was to eliminate the underscores in the module names altogether. (This was the behavior of the original discovery-openapi converter and swagger generator.) …
=> fix: shorten double-underscores in model class references

lib/google_apis/generator/elixir_generator.ex, lib/google_apis/generator/elixir_generator/api.ex, lib/google_apis/generator/elixir_generator/model.ex, lib/google_apis/generator/elixir_generator/token.ex
Fixes #2435 
The compute API has several models that map to the same file name: `HttpHealthCheck` and `HTTPHealthCheck` both generate as `http_health_check.ex`. So in the generator, one would overwrite the other, and so one would be missing from the final generated library. Same with `HttpsHealthCheck` and `HTTPSHealthCheck`.
This PR does an analysis looking for duplicated filenames (in models and apis), and dedups them by adding `_1`, `_2` etc. to the filename if it already exists. It also sorts the inputs to ensure that input ordering doesn't change which module gets assigned which filename.
=> fix: dedup generated model and api filenames

lib/google_apis/generator/elixir_generator.ex, lib/google_apis/generator/elixir_generator/endpoint.ex
Fixes #2436 
Some resource names have hyphens, which is currently messing with codegen since an Elixir function name cannot (easily) include hyphens. This currently affects the GKE API.
This PR replaces hyphens with underscores when generating function names.
=> fix: handle resource names with hyphens

lib/google_apis/generator/elixir_generator/model.ex
Fixes #2438 
IdentityToolkit is failing to generate properly because the `IdentitytoolkitRelyingpartyGetPublicKeysResponse` resource in the discovery doc has no `properties` field. This may technically be an error in the discovery doc, but we can work around it by generating the model if the resource has an ID even if it is missing properties (by assuming the property list is empty).
=> fix: handle resource types without any properties

clients/gax/README.md, clients/gax/lib/google_api/gax/connection.ex, clients/gax/mix.exs, clients/gax/test/gax/api_test.exs
It looks like some APIs (notably discovery) are starting to return responses with `content-encoding: gzip`. We need to handle this case.
=> fix: handle responses with compressed content-encoding

lib/google_apis/generator/elixir_generator/endpoint.ex, test/google_apis/generator/elixir_generator/endpoint_test.exs
If you skip decoding, API calls can return `{:ok, Tesla.Env.t()}`. Make sure this is part of the generated typespec. Fixes #2624
=> fix: api response typespecs reflect the option to skip decoding

lib/google_apis/generator/elixir_generator.ex
This is a hack for the admin library, which currently has a malformed documentation link (i.e. a relative rather than absolute URL) and thus has not been able to release to hex.
=> fix: hack docs link for admin

lib/google_apis/discovery.ex
It turns out that #4065 did not actually fix the synth of Tasks and Blogger because the code that downloads the discovery doc doesn't use the discovery API. So I had to add the DecompressResponse middleware to the generator code that does that download.
Tested this against the actual responses for Tasks to verify that it does fix the issue.
=> fix: decompress discovery docs on download

lib/google_apis/change_analyzer.ex
The change analysis that determines whether a change should be minor or patch, isn't working for libraries that include more than one version of an API. Those changes are always being classified as minor, even if the individual changes are documentation-only. The reason is:
* First version gets generated. It is classified as patch, and the version constant gets its patchlevel bumped in `mix.exs`.
* Second version gets generated. The classifier notices that `mix.exs` has had non-documentation updated (specifically the version constant) and thus reclassifies the overall change as minor.
This PR omits the version constant in the `mix.exs` file from the change analyzer. (It still recognizes other `mix.exs` changes, and will still recognize any `@version` constant in any other file.)
=> fix: Previous version bumps should not trigger minor changes

lib/google_apis/generator/elixir_generator/endpoint.ex, test/google_apis/generator/elixir_generator/endpoint_test.exs
Tesla generally passes through whatever error detail term is emitted by the underlying adapter, which could probably be any arbitrary type. Adjusting the typespec accordingly. (See #4453)
=> fix: Tesla errors can be any type

lib/google_apis/generator/elixir_generator.ex
I realized I missed the case where the discovery doc doesn't change but the generator does. So we still need to run generation if the discovery revision is _equal_ to the previous revision. We disable generation only if we got an _older_ discovery doc.
=> fix: Allow regeneration based on generator changes

synth.py
So we can see generation script output, for troubleshooting autosynth issues.
=> chore: Show output from the docker command during synth

synth.py
I think this should fix all the autosynth failures (e.g. #4985).
What seems to be happening is, when we moved autosynth into the synthtool code base, we merged the git logic. In particular, autosynth now uses synthtool's git class to do its cloning of the target repo (see https://github.com/googleapis/synthtool/blob/master/autosynth/synth.py#L518). This caused a problem for Elixir because Elixir's synth script does a second clone using the same class—thus cloning to the same directory. That is, the second clone clobbers the first, and the later logic gets confused because it wants to copy changes from one clone to the other.
This fix simply does away with the second clone, and performs modifications to the repo "in place". I do not believe the second clone is necessary any longer, …
=> fix: Run synth in the current repo clone

lib/google_apis.ex, lib/google_apis/change_analyzer.ex, lib/google_apis/generator.ex, lib/mix/tasks/google_apis.generate.ex
After I made the change to store the discovery revision in the generated client (to ensure we don't regen a client from an earlier revision due to gradual discovery rollout), I ran into another issue. It is very common for new revisions of discovery documents to be released, with a change to the discovery revision (and also presumably the etag) but no other change. As a result, we're now getting dozens of PRs per day where the only change is that the discovery revision is updated. Example: https://github.com/googleapis/elixir-google-api/pull/5023/files
This change suppresses those PRs. At the end of generation, it runs an analysis of the change, and if the change includes only a discovery_revision bump and nothing else, it reverts the change and does not open a PR. Note that if multiple …
=> feat: Roll back change if it's only a discovery revision

config/apis.json
V2 and V4 discovery docs are no more, but V5 is still present (see #5292)
=> fix: Remove PageSpeedOnline v2 and v4 from the list

clients/gax/lib/google_api/gax/model_base.ex, clients/gax/mix.exs, clients/gax/test/gax/api_test.exs, clients/gax/test/test_client/model/pet.ex
We've identified at least one case of a field being of type array of array of object (#3409) which is not supported by the gax ModelBase. This PR updates gax to support this case. A follow-up PR will update the generator to use this capability, once we release the gax update.
=> feat(gax): Support decoding a list of lists

clients/test_client/lib/google_api/test_client/v1/model/nested_container.ex, clients/test_client/mix.exs, clients/test_client/test/type_test.exs, lib/google_apis/generator/elixir_generator.ex, lib/google_apis/generator/elixir_generator/model.ex, lib/google_apis/generator/elixir_generator/resource_context.ex, lib/google_apis/generator/elixir_generator/type.ex, template/elixir/mix.exs.eex, template/elixir/model.ex.eex, test/google_apis/generator/elixir_generator/model_test.exs
This PR depends on #5686, and, in combination with that one, is meant to address #3409. The issue is that a _resource_ has an array type rather than an object type. (There seems to be only one case of this that I've found in our current set of discovery documents.) As a result, when a field references that resource, it needs to know to wrap the type in an extra list.
The solution is in two parts:
1. Support a "list of lists" type to handle nested arrays properly. #5686 adds this type (`:listlist`) to the gax ModelBase and provides the code necessary to deserialize it. Then, this PR adds the model type `"arrayarray"` and responds by generating a `:listlist` field. Together, these will catch nested array specifications in the discovery doc and generate the correct types.
2. Handle the …
=> fix(generator): Correctly handle array-typed resources

lib/google_apis/generator/elixir_generator/endpoint.ex, template/elixir/api.ex.eex
If a method sets `supportsMediaDownload`, add special behavior in the generated code where if `alt: "media"` is set, we also set the `decode: false` option by default. This addresses the standard media download behavior that downloads raw content if the `alt=media` query parameter is used. See #3573.
=> fix(generator): Skip response decoding by default on download methods when alt=media is set

lib/google_apis/change_analyzer.ex
I noticed that changes that affect only `@moduledoc` annotations were not getting through. This is because the ChangeAnalyzer is trying to recognize changes that involve only an update to the discovery revision and nothing else, and is treating those as no-op changes and preventing them from opening PRs. Except the ChangeAnalyzer had a bug where a `@moduledoc` change was incorrectly classified as not being a documentation change. (More specifically, when the ChangeAnalyzer checked whether a change was "discovery-revision-only", it incorrectly ignored `@moduledoc` changes.) This PR fixes the logic so `@moduledoc` changes are ignored only when distinguishing "documentation-only" from "significant change".
=> fix(generator): Don't throw away changes that affect only moduledoc

lib/google_apis/generator/elixir_generator/resource_context.ex, lib/google_apis/generator/elixir_generator/token.ex, test/google_apis/generator/elixir_generator/resource_context_test.exs
Currently, we prefer that the baseUrl include the service path for most cases. However, if a service includes any media upload, those paths are specified as absolute (i.e. do not respect the service path) and therefore the baseUrl cannot include the service path. So those cases use a baseUrl with an empty path, and prepend the service path to the method path.
It turns out there are a few other cases where a method path is specified as absolute (see #4477). So we expand the logic to check for _any_ absolute method paths in addition to the presence of media upload. We also update the ResourceContext path concatenation logic to respect absolute paths. This should fix #4477 after regeneration.
=> fix(generator): Base URL path should be empty if any method path is absolute

lib/google_apis/generator/elixir_generator.ex
Tasks library is failing to publish because the Homepage link is the empty string. This is because the documentationLink in the discovery doc is the empty string. Handle this case in the generator: use a default link if documentationLink is empty.
=> fix(generator): Ensure homepage link is not empty

lib/google_apis/change_analyzer.ex
I've seen a few cases where documentation-only changes are being classified as significant changes because they affect the description in `mix.exs`. This modifies the change analyzer so that if that particular function looks as we expect, then changes to it are treated as documentation-only.
=> fix(generator): Change analyzer classifies description changes as documentation-only

.github/workflows/presubmit.yml, lib/mix/tasks/presubmit.ex
I'm moving presubmit (and only presubmit for now) to GH actions. The main reason is better support for analysis of the PR and its diffs.
The GH actions version of the presubmit job has been enhanced to determine which clients have changed in the PR, and run `mix do deps.get, test` for those (and only those) clients. (Previously, only TestClient and Gax were actually tested.)
Once this is stable, I'll remove the kokoro presubmit. This is also a prerequisite for implementing autoapprove.
=> chore: Implement full presubmit checks in GH actions

config/apis.json, config/exceptions.json, lib/google_apis/discovery.ex
Fixes #6099 
Also updates the discover script to handle additional cases. These are targeted toward eventual (partial) automation of this process.
* Supports exceptions: both APIs that don't exist but still show up in discovery (like plus v1) and APIs that aren't in discovery but we want to keep for now (like oauth2 v2).
* Detects URL changes and calls them out as such rather than showing up as a deletion and separate addition
* Attempts to guess at a capitalization for new entries, especially if it is a new version of an already existing API where we already know what the capitalization ought to be.
=> chore: Update apis.json
